### ISSUE TITLE
Actualización de bootstrap

### ISSUE THREAD

**Issue by JGuerreroS** [systemsPNB/extranet#2]
Hermano bootstrap acaba de lanzar la versión 4.1.3.

Por favor actualizar el archivo de bootstrap ubicado en:
views/css/bootstrap.min.css
por el del siguiebte CDN:
https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css

Ojo guardar con el mismo nombre, borrar el archivo anterior y reemplazar por este nuevo

**Comment by eudomars** [comment]
ok, en cuanto haga la actualice te informo

**Comment by eudomars** [comment]
ya modifique la versión de booststrap 4.1.3, y subí los cambios
