### ISSUE TITLE
Crear vista PDF del ARC

### ISSUE THREAD

**Issue by JGuerreroS** [systemsPNB/extranet#3]
Crear vista para el PDF del arc, existe un modelo de como debe lucir en la carpeta 
views/img/planilla_arc.pdf

**Comment by JGuerreroS** [comment]
Listo, se creo la vista ARC, falta agregarle el funcionamiento

**Comment by eudomars** [comment]
listo el funcionamiento, del botón generar ARC, solo faltaría la consulta
